{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "samba-adc.serviceAccountName" . }}
  labels:
{{ include "samba-adc.labels" . | indent 4 }}
{{- end -}}
